name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Lint check 
      run: ./gradlew lint
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
    - name: Connected Test
      uses: vgaidarji/android-github-actions/emulator@v1.0.0
    - name: Build with Gradle
      run: ./gradlew build
