name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Lint check 
      run: ./gradlew lint
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
    - name: Build with Gradle
      run: ./gradlew build
  unitTest:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
  connectedTest:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout google/cloud-sdk
      uses: docker://google/cloud-sdk:latest
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/checkout@v1
    - name: setup google cloud sdk
      env:
        GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        GOOGLE_PROJECT_ID: github-actions-test-lab
        GOOGLE_COMPUTE_ZONE: asia-northeast2
      run: echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
    - name: Build with Gradle
      run: ./gradlew assembleDebug assembleDebugAndroidTest
    - name: test on firebase test lab
      run: sudo gcloud firebase test android run
              --app /app/build/outputs/apk/debug/app-debug.apk
              --test /app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
              
    
    
