name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
    - name: Build with Gradle
      run: ./gradlew build
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Lint check 
      run: ./gradlew lint
  unitTest:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
  connectedTest:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Connected Test
      uses: vgaidarji/android-github-actions/emulator@v1.0.0
    
